#!/bin/bash

#########################################
#                                       #
#            LUCIA INSTALLER            #
#                                       #
#########################################


LUCIA_INSTALL_DIRECTORY=$HOME/Lucia-Notify


echo '[*] Installing dependencies...'
sudo apt install libmysqlclient-dev libdbi-perl libdbd-mysql-perl -y &>/dev/null 
echo 'yes local::lib' | sudo cpan Net::DBus Dotenv File::Which &>/dev/null
if [ $? -ne 0 ]; then
    echo '[x] An error occurred while installing dependencies'
    exit 1
fi
echo '[+] Dependencies installed'


mkdir $LUCIA_INSTALL_DIRECTORY &>/dev/null
if [ $? -ne 0 ]; then
    rm --recursive --force $LUCIA_INSTALL_DIRECTORY
    mkdir $LUCIA_INSTALL_DIRECTORY
fi
echo '[+] Directory created'


cp --recursive . $LUCIA_INSTALL_DIRECTORY
echo '[+] Files copied'


echo "export PATH=$PATH:$LUCIA_INSTALL_DIRECTORY/scripts" >> ~/.bashrc

echo '[+] Lucia Notify has been installed'
