#!/bin/bash

#########################################
#                                       #
#            LUCIA INSTALLER            #
#                                       #
#########################################


LUCIA_INSTALL_DIRECTORY=$HOME/Lucia-Notify

echo '[*] Adding Perl repository to APT...'
sudo add-apt-repository universe
echo '[*] Installing general dependencies...'
sudo apt install cpanminus libmysqlclient-dev libdbi-perl libdbd-mysql-perl mpg123 -y &>/dev/null
echo '[*] Installing Perl dependencies with CPANM'
sudo cpanm Net::DBus Dotenv File::Which Audio::Play::MPG123 LWP::Simple JSON JSON::MaybeXS &>/dev/null
if [ $? -ne 0 ]; then
    echo '[x] An error occurred while installing dependencies'
    exit 1
fi
echo '[+] Dependencies installed'


mkdir $LUCIA_INSTALL_DIRECTORY &>/dev/null
if [ $? -ne 0 ]; then
    rm --recursive --force $LUCIA_INSTALL_DIRECTORY
    mkdir $LUCIA_INSTALL_DIRECTORY
fi
echo '[+] Directory created'


cp --recursive . $LUCIA_INSTALL_DIRECTORY
echo '[+] Files copied'


echo '[+] Lucia Notify has been installed'
