#!/usr/bin/perl

use strict;
use warnings;

use lib '../lib';
use Lucia::BugChurch::Proxy;

my $bcp = Lucia::BugChurch::Proxy->new;
$bcp->use_model('bug');
my $bugs = $bcp->get_bugs_by_ids('3123123');

use Data::Dumper;
print Dumper $bugs;
