#!/usr/bin/perl

use strict;
use warnings;

use lib '../lib';
use Lucia::BugTrackerClient;

my $btc = Lucia::BugTrackerClient->new( 'localhost', 3000 );
my @bugs = @{$btc->get_bugs_by_ids('1232,41214,54345')};
