#!/usr/bin/perl

use strict;
use warnings;

use lib '../lib';
use Lucia::Lucia;

my $lucia = Lucia::Lucia->new;
$lucia->set_lang('en');
$lucia->set_time(10);
$lucia->enable_sound(0);
$lucia->enable_voice(1);
$lucia->enable_no_greeting(1);
$lucia->enable_debug(1);

#$lucia->simulate( '1732853244' );
#$lucia->notify_for_bugs( '17423' );
$lucia->notify_for_user( 'mmartel' );
