#!/bin/bash

SCRIPT=$(realpath "$0")
LUCIA_DIR="$(dirname "$SCRIPT")/.."

export $(grep -v '^#' $LUCIA_DIR/.env | xargs -d '\n')

if   [[ "$LUCIA_USER_COMMAND" = true ]]; then MAIN_PARAM="user $LUCIA_USERNAME" 
elif [[ "$LUCIA_BUGS_COMMAND" = true ]]; then MAIN_PARAM="bugs $LUCIA_BUGS"
else
    echo 'Cant continue if you dont set a main option'
    exit 1
fi

if [[ "$LUCIA_SOUND" = true ]]; then SOUND_PARAM='--sound'; fi
if [[ "$LUCIA_NOBANNER" = true ]]; then BANNER_PARAM='--no-banner'; fi
if [[ "$LUCIA_NOGREETING" = true ]]; then GREETING_PARAM='--no-greeting'; fi
if [[ "$LUCIA_VOICE" = true ]]; then VOICE_PARAM='--voice'; fi

LANG_PARAM="--lang $LUCIA_LANG"

$LUCIA_DIR/bin/lucia $MAIN_PARAM $SOUND_PARAM --time $LUCIA_TIME $BANNER_PARAM $GREETING_PARAM $VOICE_PARAM $LANG_PARAM
