#!/bin/bash

# Script that will check if there is an active X11 session. 
# Lucia will be started after this has been confirmed to use that session.

while [ 1 ]; do

  # Check whether or not socket exists
  if [ -S /tmp/.X11-unix/X0 ]; then exit 0; fi

  sleep 1

done
